name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js for server
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install server dependencies
      working-directory: ./server
      run: npm ci

    - name: Set up Node.js for client
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install client dependencies
      working-directory: ./client
      run: npm ci

    - name: Build client app
      working-directory: ./client
      run: npm run build

    - name: Add SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/${{ secrets.PEM_FILE_NAME }}
        chmod 600 ~/.ssh/${{ secrets.PEM_FILE_NAME }}

    - name: Transfer server files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.PEM_FILE_NAME }} -r ./server ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/deploy/server



    - name: Transfer client build files to EC2
      run: |
        scp  -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.PEM_FILE_NAME }} -r
        ./client/build ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/deploy/client


    - name: Transfer client build files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.PEM_FILE_NAME }} -r ./client/build ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/deploy/client


    - name: Deploy to EC2
      run: |
        ssh  -o StrictHostKeyChecking=no -i ~/.ssh/${{ secrets.PEM_FILE_NAME }} ${{
        secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          # Move server files to the appropriate directory
          sudo mkdir -p /var/www/server
          sudo mv /home/${{ secrets.EC2_USER }}/deploy/server/* /var/www/server/

          # Move client build files to the appropriate directory
          sudo mkdir -p /var/www/html
          sudo mv /home/${{ secrets.EC2_USER }}/deploy/client/* /var/www/html/

          # Restart the PM2 process for the server
          pm2 restart /var/www/server/index.js --name my-server

          # Restart Nginx to serve the new build
          sudo systemctl restart nginx
        EOF
